# ==============================================================================
# ORDERS SERVICE
# Production Environment Overrides
# ==============================================================================

replicaCount: 1

image:
  repository: tcollins520/retail-store-orders
  pullPolicy: IfNotPresent
  tag: "sha-4ea8b6d-1"

app:
  persistence:
    provider: postgres
    database: ordersdb

    secret:
      name: orders-db

messaging:
  provider: sqs

  sqs:
    topic: prod-orders-queue

database:
  endpoint: prod-orders-postgresql.cifguuuaskpf.us-east-1.rds.amazonaws.com
  port: 5432
  serviceName: orders-postgres

secrets:
  awsRegion: us-east-1
  secretName: prod/orders/database
  secretProviderClass: orders-db-secrets
