# ==============================================================================
# UI SERVICE
# Production Environment Overrides
# ==============================================================================

replicaCount: 1

image:
  repository: tcollins520/retail-store-ui
  pullPolicy: IfNotPresent
  tag: "sha-fa15711-2"

app:
  theme: default

  endpoints:
    catalog: http://catalog
    carts: http://carts
    checkout: http://checkout
    orders: http://orders

ingress:
  enabled: true

  className: alb

  hostname: shop-v3.tinacloud.dev

  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:801242830567:certificate/f1c53ba0-38c2-43b3-9513-2bd356199caf
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/success-codes: "200"
    external-dns.alpha.kubernetes.io/hostname: shop-v3.tinacloud.dev
