# ==============================================================================
# CATALOG SERVICE
# Production Environment Overrides
# ==============================================================================

replicaCount: 1

image:
  repository: tcollins520/retail-store-catalog
  pullPolicy: IfNotPresent
  tag: "sha-e8f25fd-4"

app:
  persistence:
    provider: mysql
    database: catalogdb

    secret:
      name: catalog-db

database:
  endpoint: production-catalog-mysql.cifguuuaskpf.us-east-1.rds.amazonaws.com
  port: 3306
  serviceName: catalog-mysql

secrets:
  awsRegion: us-east-1
  secretName: production/catalog/database
  secretProviderClass: catalog-db-secrets
