# ==============================================================================
# CHECKOUT SERVICE
# Production Environment Overrides
# ==============================================================================

replicaCount: 1

image:
  repository: tcollins520/retail-store-checkout
  pullPolicy: IfNotPresent
  tag: "sha-9654178-1"

app:
  persistence:
    provider: redis
    redisUrl: "redis://prod-checkout-redis.m7f8mc.0001.use1.cache.amazonaws.com:6379"

  endpoints:
    orders: http://orders
