apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - traces-collector.yaml
  - logs-collector.yaml
  - metrics-collector.yaml
  - instrumentation.yaml