apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: ui
  namespace: argocd

spec:
  project: retail-store-v3-production

  sources:
    # Helm chart source
    - repoURL: https://github.com/tcollins520/retail-store-v3-engineering.git
      targetRevision: main
      path: helm/ui

      helm:
        releaseName: ui
        valueFiles:
          - $values/environments/production/ui/values.yaml

    # Production values source
    - repoURL: https://github.com/tcollins520/retail-store-v3-gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:

    syncOptions:
      - CreateNamespace=true
